# Generated by Django 4.1.5 on 2023-01-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, upload_to='spots/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, upload_to='locations/'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='num_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
