# Generated by Django 4.1.5 on 2023-01-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_remove_spot_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, upload_to='spots/image/%Y/%m/%d/'),
        ),
    ]
